### ISSUE TITLE
importing model is failing

### ISSUE THREAD

**Issue by MikeRD03** [WARP-LAB/files_3dmodelviewer#11] opened 2023-04-13 10:49 UTC
## Describe the bug

I am using 3D viewer in my v25 snap installation. Once I try to open any STEP file it displays "importing..." forever.

## To Reproduce

Just open any STEP file

## Expected behavior

expected to see a 3D model preview

## I have checked that the files are not corrupted

Yes, using Autodesk Inventor and SW eDrawings. Tried many different files. All without issues in these desktop apps.

## Browser log

There is an error in the browser log (Opera 64bit):

occt-import-js.js:1 Uncaught (in promise) TypeError: err is not a function
    at occt-import-js.js:1:162214

### How the app was installed?

- Via app store.

### App server configuration Parameters

- `apps_path` parameter is not explicitly configured/customised in `config/config.php`

### Nextcloud

- Version:  25.0.4 
- Webserver: Apache

### Desktop

Opera Browser, most recent version
also tried Edge and Firefox with same result

**Comment by kroko** [comment] 2023-04-14 15:17
I assume the error is observed only for STEP (and probably IFC), other supported formats do load, correct?

**Comment by kroko** [comment] 2023-04-14 17:17
Installed Nextcloud via snap, can replicate.

It seems that the issue is that `/snap/nextcloud/current/conf/mime.types` does not hold WebAssembly MIME.

Can be traced upstream via https://github.com/nextcloud-snap/nextcloud-snap/blob/master/snap/snapcraft.yaml back to Apache source https://github.com/apache/httpd/blob/trunk/docs/conf/mime.types

1)
To solve this issue the right way (IMHO 😄 ), please contribute to Apache - they should add `wasm` mime type and then wait till it populates down the chain to NC snap. All other ways are hacks.

_httpd/docs/conf/mime.types_
```
application/wasm wasm
```

2)
A faster way might be adding

```apache
AddType application/wasm wasm
```

to https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/apache/conf/httpd.conf#L187 as that is controlled by NC not Apache upstream.

3)
The fastest way would be dropping Snap.

**Comment by kroko** [comment] 2023-04-18 01:29
@MikeRD03 did PR to NC snap repo, will see if/how fast it populates to you.

**Comment by kroko** [comment] 2023-04-20 21:48
@MikeRD03, please update to 25.0.6snap1 and check if WASM stuff works now. closing, if anything this can be reopened.

**Closed by kroko** 2023-04-20 21:48 UTC
Labels: bug, upstream

**Comment by MikeRD03** [comment] 2023-04-21 17:14
updated and working with 25.0.6! Thank you! MikeRD03
