### ISSUE TITLE
Other users cant view model

### ISSUE THREAD

**Issue by kevensavard** [WARP-LAB/files_3dmodelviewer#23] opened 2024-05-03 14:00 UTC
So i installed the app, everything's work fine for me but other users cant view the model

**Comment by kroko** [comment] 2024-05-15 07:53
as you do not give any info about your setup and/or to reproduce, will close this. maybe duplicate of (?) https://github.com/WARP-LAB/files_3dmodelviewer/issues/4

**Closed by kroko** 2024-05-15 07:53 UTC
Labels: bug
